from django.db import models

class ServerUnique(models.Model):

    # Represents the unique server, identified by his hostname.

    hostname = models.CharField(max_length=255, unique=True, verbose_name="Unique hostname")
    
    priority_asset = models.CharField(max_length=255, blank=True, null=True, verbose_name="Priority Asset")
    in_live_play = models.CharField(max_length=255, blank=True, null=True, verbose_name="In Live Play")
    action_during_lp = models.TextField(blank=True, null=True, verbose_name="Action during Live Play")
    action_during_lp_history = models.TextField(blank=True, null=True, verbose_name="Action during Live Play History")
    original_action_during_lp = models.TextField(blank=True, null=True, verbose_name="Original Action During Live Play")
    original_action_during_lp_history = models.TextField(blank=True, null=True, verbose_name="Original Action During Live Play History")
    cluster = models.CharField(max_length=255, blank=True, null=True, verbose_name="Cluster")
    cluster_type = models.CharField(max_length=255, blank=True, null=True, verbose_name="Cluster Type")
    global_history = models.JSONField(default=list, help_text="Historical entries")

    def __str__(self):
        return self.hostname

    def append_global_history(self, changes: dict, username: str, source: str) -> None:
        """
        Append a structured entry to global_history.
        Matches the format produced by BusinessContinuityInformationForm.save()
        so that the history view is consistent regardless of the edit source.

        Args:
            changes  : dict of field-level change descriptors, e.g.:
                       { 'priority_asset': {'old': 'YES', 'new': 'NO'} }
                       { 'action_during_lp': {'info': 'Updated, check its history'} }
            username : user or process name (e.g. request.user.username, 'BC Rules')
            source   : human-readable source label:
                       'Single Edit' | 'Bulk Edit' | 'CSV Import' |
                       'Application CSV Import' | 'BC Rules'

        Notes:
            - No-ops silently if changes is empty.
            - Caps global_history at 500 entries to prevent unbounded growth.
            - Does NOT call self.save() — caller is responsible for saving,
              typically via bulk_update(..., ['global_history']).
        """
        import datetime

        if not changes:
            return

        entry = {
            'date':       datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            'user':       username,
            'fromsource': source,
            'changes':    changes,
        }

        gh = self.global_history if isinstance(self.global_history, list) else []
        gh.insert(0, entry)
        self.global_history = gh[:500]

    class Meta:
        verbose_name = "Unique server"
        verbose_name_plural = "Unique servers"


class Server(models.Model):

    # Server info. Its ID is automatically generated by Django as primary key
    
    # Link to the ServerUnique information to display information relative to the hostname
    server_unique = models.ForeignKey(
        ServerUnique,
        on_delete=models.CASCADE, # if the server is deleted, its entries in ServerUnique are deleted too
        related_name='server_info', # Gives the possibility to access to Server information from ServerUnique
        verbose_name="Associated Server (Unique)"
    )

    SERVER_ID = models.CharField(max_length=100, default='UNKNOWN', db_index=True)
    ITCONTINUITY_LEVEL = models.CharField(max_length=100, null=True, blank=True)
    DAP_NAME = models.CharField(max_length=100, null=True, blank=True)
    DAP_AUID = models.CharField(max_length=100, null=True, blank=True)
    DATACENTER = models.CharField(max_length=100, null=True, blank=True)
    TECH_FAMILY = models.CharField(max_length=100, null=True, blank=True)
    MACHINE_TYPE = models.CharField(max_length=100, null=True, blank=True)
    VM_TYPE = models.CharField(max_length=100, null=True, blank=True)
    AFFINITY = models.CharField(max_length=100, null=True, blank=True)
    DATABASE_TECHNO = models.CharField(max_length=100, null=True, blank=True)
    DATABASE_DB_CI = models.CharField(max_length=255, null=True, blank=True)
    VITAL_LEVEL = models.CharField(max_length=100, null=True, blank=True)
    SUPPORT_GROUP = models.CharField(max_length=255, null=True, blank=True)
    APPLICATION_SUPPORT_GROUP = models.CharField(max_length=255, null=True, blank=True)
    IT_CLUSTER = models.CharField(max_length=100, null=True, blank=True)
    COUNTRY = models.CharField(max_length=100, null=True, blank=True)


    def __str__(self):
        return f"{self.SERVER_ID} - App: {self.DAP_NAME} (ID: {self.id})"

    class Meta:
        verbose_name = "Server entry"
        verbose_name_plural = "Server entries"

  
class ServerStaging(models.Model):

    # Server info. Its ID is automatically generated by Django as primary key
    
    # Link to the ServerUnique information to display information relative to the hostname
    server_unique = models.ForeignKey(
        ServerUnique,
        on_delete=models.CASCADE, # if the server is deleted, its entries in ServerUnique are deleted too
        related_name='server_info_staging', # Gives the possibility to access to Server information from ServerUnique
        verbose_name="Associated Server (Unique)"
    )

    SERVER_ID = models.CharField(max_length=100, default='UNKNOWN', db_index=True)
    ITCONTINUITY_LEVEL = models.CharField(max_length=100, null=True, blank=True)
    DAP_NAME = models.CharField(max_length=100, null=True, blank=True)
    DAP_AUID = models.CharField(max_length=100, null=True, blank=True)
    DATACENTER = models.CharField(max_length=100, null=True, blank=True)
    TECH_FAMILY = models.CharField(max_length=100, null=True, blank=True)
    MACHINE_TYPE = models.CharField(max_length=100, null=True, blank=True)
    VM_TYPE = models.CharField(max_length=100, null=True, blank=True)
    AFFINITY = models.CharField(max_length=100, null=True, blank=True)
    DATABASE_TECHNO = models.CharField(max_length=100, null=True, blank=True)
    DATABASE_DB_CI = models.CharField(max_length=255, null=True, blank=True)
    VITAL_LEVEL = models.CharField(max_length=100, null=True, blank=True)
    SUPPORT_GROUP = models.CharField(max_length=255, null=True, blank=True)
    APPLICATION_SUPPORT_GROUP = models.CharField(max_length=255, null=True, blank=True)
    IT_CLUSTER = models.CharField(max_length=100, null=True, blank=True)
    COUNTRY = models.CharField(max_length=100, null=True, blank=True)


    def __str__(self):
        return f"{self.SERVER_ID} - App: {self.DAP_NAME} (ID: {self.id})"

    class Meta:
        verbose_name = "Server entry Staging"
        verbose_name_plural = "Server entries Staging"
        managed = False


class ImportStatus(models.Model):
    date_import = models.DateTimeField(auto_now_add=True)
    success = models.BooleanField(default=False)
    message = models.TextField(blank=True, null=True)
    nb_entries_created = models.IntegerField(default=0)
    source_url = models.URLField(blank=True, null=True)

    def __str__(self):
        return f"{'OK' if self.success else 'KO'} {self.date_import.strftime('%d.%m.%Y %H:%M')}"


class BCRuleTexts(models.Model):
    """
    Stores the user-defined action texts for each BC decision rule.
    One row per rule_key — updated in place each time the wizard is applied.
    A single set of texts is shared across all datacenters (one DR at a time).
    """

    rule_key    = models.CharField(
        max_length=50,
        unique=True,
        db_index=True,
        help_text="BC rule identifier — matches constants in bc_rules_logic.py",
    )
    action_text = models.TextField(
        help_text="Text written into action_during_lp for servers matching this rule",
    )
    updated_at  = models.DateTimeField(auto_now=True)
    updated_by  = models.CharField(
        max_length=150,
        blank=True,
        help_text="Username of the last editor",
    )

    class Meta:
        verbose_name        = "BC Rule Text"
        verbose_name_plural = "BC Rule Texts"
        ordering            = ["rule_key"]

    def __str__(self):
        return f"{self.rule_key}: {self.action_text[:60]}"
