# Generated by Django 6.0.1 on 2026-06-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OBJECT_ID', models.CharField(db_index=True, max_length=255, unique=True)),
                ('comment', models.TextField(blank=True)),
                ('assigned_to', models.CharField(blank=True, max_length=150)),
                ('history', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShareAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SHARE_ID', models.CharField(db_index=True, max_length=255, unique=True)),
                ('comment', models.TextField(blank=True)),
                ('assigned_to', models.CharField(blank=True, max_length=150)),
                ('history', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageImportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('nb_entries_created', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StorageObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(db_column='object_id', db_index=True, max_length=255)),
                ('NAME', models.CharField(blank=True, max_length=500, null=True)),
                ('PROTOCOL', models.CharField(blank=True, max_length=100, null=True)),
                ('ALLOCATION', models.CharField(blank=True, max_length=100, null=True)),
                ('USAGE', models.CharField(blank=True, max_length=100, null=True)),
                ('APPLICATION_NAME', models.CharField(blank=True, max_length=500, null=True)),
                ('BAM_VALUE', models.CharField(blank=True, max_length=255, null=True)),
                ('AUID_VALUE', models.CharField(blank=True, max_length=255, null=True)),
                ('ENVIRONMENT', models.CharField(blank=True, max_length=100, null=True)),
                ('REGION', models.CharField(blank=True, max_length=100, null=True)),
                ('COUNTRY', models.CharField(blank=True, max_length=100, null=True)),
                ('SCOPE', models.CharField(blank=True, max_length=255, null=True)),
                ('ECOSYSTEM', models.CharField(blank=True, max_length=100, null=True)),
                ('IT_CLUSTER', models.CharField(blank=True, max_length=255, null=True)),
                ('IT_SUBCLUSTER', models.CharField(blank=True, max_length=255, null=True)),
                ('IN_S3_REF', models.CharField(blank=True, max_length=50, null=True)),
                ('IN_CAPSULE_REF_S3', models.CharField(blank=True, max_length=50, null=True)),
                ('CAPSULE_SPECIAL_USECASE', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ID'], name='storage_sto_object__f1b146_idx'), models.Index(fields=['PROTOCOL'], name='storage_sto_PROTOCO_f3a72b_idx'), models.Index(fields=['ENVIRONMENT'], name='storage_sto_ENVIRON_b5b636_idx'), models.Index(fields=['REGION'], name='storage_sto_REGION_5dce5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='StorageShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(db_column='share_id', db_index=True, max_length=255)),
                ('PROVIDER', models.CharField(blank=True, max_length=100, null=True)),
                ('CLUSTER', models.CharField(blank=True, max_length=255, null=True)),
                ('FILER', models.CharField(blank=True, max_length=255, null=True)),
                ('SHARE_NAME', models.CharField(blank=True, max_length=500, null=True)),
                ('SHARE_REAL_NAME', models.CharField(blank=True, max_length=500, null=True)),
                ('SHARE_PATH', models.CharField(blank=True, max_length=1000, null=True)),
                ('VOLUME', models.CharField(blank=True, max_length=255, null=True)),
                ('PROTOCOL', models.CharField(blank=True, max_length=100, null=True)),
                ('IP_ADDRESS', models.CharField(blank=True, max_length=100, null=True)),
                ('UUID', models.CharField(blank=True, max_length=255, null=True)),
                ('CONSUMER_TYPE', models.CharField(blank=True, max_length=100, null=True)),
                ('ALLOCATION', models.CharField(blank=True, max_length=100, null=True)),
                ('USAGE', models.CharField(blank=True, max_length=100, null=True)),
                ('APPLICATION_NAME', models.CharField(blank=True, max_length=500, null=True)),
                ('BAM_VALUE', models.CharField(blank=True, max_length=255, null=True)),
                ('APPLICATION_AUID_VALUE', models.CharField(blank=True, max_length=255, null=True)),
                ('ENVIRONMENT', models.CharField(blank=True, max_length=100, null=True)),
                ('IS_OPEN', models.CharField(blank=True, max_length=50, null=True)),
                ('OPEN_SHARE_EXCEPTION', models.CharField(blank=True, max_length=50, null=True)),
                ('REGION', models.CharField(blank=True, max_length=100, null=True)),
                ('COUNTRY', models.CharField(blank=True, max_length=100, null=True)),
                ('SCOPE', models.CharField(blank=True, max_length=255, null=True)),
                ('ECOSYSTEM', models.CharField(blank=True, max_length=100, null=True)),
                ('VITAL_APPLICATION', models.CharField(blank=True, max_length=50, null=True)),
                ('IT_CLUSTER', models.CharField(blank=True, max_length=255, null=True)),
                ('IT_SUBCLUSTER', models.CharField(blank=True, max_length=255, null=True)),
                ('IN_NAS_REF', models.CharField(blank=True, max_length=50, null=True)),
                ('IN_NETAPP_SCANNER', models.CharField(blank=True, max_length=50, null=True)),
                ('IN_NAS_CAPSULE', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ID'], name='storage_sto_share_i_9d3d71_idx'), models.Index(fields=['PROVIDER'], name='storage_sto_PROVIDE_d2bff7_idx'), models.Index(fields=['ENVIRONMENT'], name='storage_sto_ENVIRON_ffd05e_idx'), models.Index(fields=['REGION'], name='storage_sto_REGION_efe26c_idx')],
            },
        ),
    ]
