# Generated by Django 6.0.1 on 2026-06-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        # StorageObject: swap index from ID to NAME
        migrations.RemoveIndex(
            model_name='storageobject',
            name='storage_sto_object__f1b146_idx',
        ),
        # StorageShare: remove old index on ID (new one on SHARE_NAME added below)
        migrations.RemoveIndex(
            model_name='storageshare',
            name='storage_sto_share_i_9d3d71_idx',
        ),
        # ShareAnnotation: rename SHARE_ID → share_key (composite key FILER|SHARE_PATH)
        migrations.RenameField(
            model_name='shareannotation',
            old_name='SHARE_ID',
            new_name='share_key',
        ),
        migrations.AlterField(
            model_name='shareannotation',
            name='share_key',
            field=models.CharField(db_index=True, max_length=1500, unique=True),
        ),
        # ObjectAnnotation: rename OBJECT_ID → NAME
        migrations.RenameField(
            model_name='objectannotation',
            old_name='OBJECT_ID',
            new_name='NAME',
        ),
        # StorageObject: drop db_index on ID, add it on NAME
        migrations.AlterField(
            model_name='storageobject',
            name='ID',
            field=models.CharField(db_column='object_id', max_length=255),
        ),
        migrations.AlterField(
            model_name='storageobject',
            name='NAME',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        # StorageShare: drop db_index on ID, add it on SHARE_NAME
        migrations.AlterField(
            model_name='storageshare',
            name='ID',
            field=models.CharField(db_column='share_id', max_length=255),
        ),
        migrations.AlterField(
            model_name='storageshare',
            name='SHARE_NAME',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='storageobject',
            index=models.Index(fields=['NAME'], name='storage_sto_NAME_96989a_idx'),
        ),
        migrations.AddIndex(
            model_name='storageshare',
            index=models.Index(fields=['SHARE_NAME'], name='storage_sto_SHARE_N_118868_idx'),
        ),
    ]
