# Generated by Django 6.0.1 on 2026-06-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_remove_storageobject_storage_sto_object__f1b146_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectannotation',
            name='NAME',
            field=models.CharField(db_index=True, max_length=500, unique=True),
        ),
    ]
